import type {
  LostItem,
  FoundItem,
  Notification,
  RecoveryStory,
  TopHelper,
  Partner,
  Category,
  MapMarker,
  FeedPost,
} from "./types";

export const CATEGORIES: Category[] = [
  { id: "1", label: "Electronics", icon: "smartphone", color: "#3B82F6" },
  { id: "2", label: "Bags", icon: "briefcase", color: "#8B5CF6" },
  { id: "3", label: "Wallet", icon: "credit-card", color: "#10B981" },
  { id: "4", label: "Keys", icon: "key", color: "#F59E0B" },
  { id: "5", label: "Documents", icon: "file-text", color: "#EF4444" },
  { id: "6", label: "Jewellery", icon: "circle", color: "#EC4899" },
  { id: "7", label: "Pets", icon: "heart", color: "#06B6D4" },
  { id: "8", label: "Other", icon: "more-horizontal", color: "#6B7280" },
];

export const LOST_ITEMS: LostItem[] = [
  {
    id: "l1",
    title: "Black Leather Backpack",
    category: "Bags",
    description: "Lost my black leather backpack near Central Bus Stand. Contains MacBook Pro, charger, and some documents. Has a red keychain attached.",
    location: "Central Bus Stand, MG Road",
    date: "2024-01-15",
    time: "10:30 AM",
    status: "active",
    images: [],
    contactName: "Ravi Kumar",
    reward: "₹2,000",
    route: "Route 42A — MG Road to Koramangala",
    userId: "u1",
    isUrgent: true,
  },
  {
    id: "l2",
    title: "iPhone 15 Pro — Space Black",
    category: "Electronics",
    description: "Lost iPhone 15 Pro with blue cover case. Screen has a small crack at the corner. Has important work data inside.",
    location: "Koramangala Metro Station",
    date: "2024-01-16",
    time: "2:15 PM",
    status: "active",
    images: [],
    contactName: "Priya Sharma",
    reward: "₹5,000",
    route: "Green Line Metro",
    userId: "u2",
    isUrgent: true,
  },
  {
    id: "l3",
    title: "Brown Leather Wallet",
    category: "Wallet",
    description: "Slim brown leather wallet with monogram 'AS'. Contains Aadhaar card, driving license, and some cash.",
    location: "City Mall Food Court",
    date: "2024-01-14",
    time: "6:45 PM",
    status: "active",
    images: [],
    contactName: "Arjun Singh",
    userId: "u3",
  },
  {
    id: "l4",
    title: "Honda Activa Keys",
    category: "Keys",
    description: "Honda Activa key with blue key ring and a small Ganesha charm attached. Also has house keys on the ring.",
    location: "Brigade Road Junction",
    date: "2024-01-16",
    time: "11:00 AM",
    status: "active",
    images: [],
    contactName: "Neha Patel",
    reward: "₹500",
    userId: "u4",
  },
  {
    id: "l5",
    title: "Golden Bracelet",
    category: "Jewellery",
    description: "22 carat gold bracelet with traditional design and tiny bell charms. Has sentimental value — grandmother's gift.",
    location: "Lalbagh Botanical Garden",
    date: "2024-01-13",
    time: "9:20 AM",
    status: "recovered",
    images: [],
    contactName: "Sunita Reddy",
    reward: "₹10,000",
    userId: "u5",
  },
  {
    id: "l6",
    title: "Passport & Documents Folder",
    category: "Documents",
    description: "Blue folder containing passport, PAN card, and travel documents. Flying tomorrow — urgent!",
    location: "Indira Gandhi Airport T2",
    date: "2024-01-17",
    time: "8:00 AM",
    status: "active",
    images: [],
    contactName: "Mehta Family",
    isUrgent: true,
    userId: "u6",
  },
];

export const FOUND_ITEMS: FoundItem[] = [
  {
    id: "f1",
    title: "Samsung Galaxy S23",
    category: "Electronics",
    description: "Found a Samsung Galaxy phone with cracked screen near the park. Phone is locked. Has a yellow silicone case.",
    foundLocation: "Cubbon Park, East Gate",
    storageLocation: "Cubbon Park Police Station",
    date: "2024-01-16",
    time: "4:30 PM",
    images: [],
    finderName: "Amit Verma",
    isVerified: true,
    partnerId: "p3",
  },
  {
    id: "f2",
    title: "Blue Denim Backpack",
    category: "Bags",
    description: "Found a blue denim backpack near the bus stop. Contains books and a water bottle. No wallet or electronics.",
    foundLocation: "Indiranagar Bus Stop 54",
    storageLocation: "Keeper's Shop — Near Bus Stop",
    date: "2024-01-15",
    time: "7:45 AM",
    images: [],
    finderName: "Kavitha R.",
    isVerified: true,
    partnerId: "p1",
  },
  {
    id: "f3",
    title: "Car Keys — Toyota",
    category: "Keys",
    description: "Toyota car keys with black fob and a small keychain. Found in the parking area.",
    foundLocation: "Forum Mall Parking, Level B2",
    storageLocation: "Forum Mall Security Office",
    date: "2024-01-17",
    time: "1:20 PM",
    images: [],
    finderName: "Security Guard",
    isVerified: true,
  },
  {
    id: "f4",
    title: "Reading Glasses",
    category: "Other",
    description: "Black rimmed reading glasses in a brown leather case. Found on a park bench.",
    foundLocation: "Ulsoor Lake Garden",
    storageLocation: "With Finder",
    date: "2024-01-16",
    time: "6:00 PM",
    images: [],
    finderName: "Deepa K.",
    isVerified: false,
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "match",
    title: "Potential Match Found!",
    message: "Your lost iPhone 15 Pro might match a found item reported at Koramangala Metro. Tap to verify.",
    time: "2 min ago",
    isRead: false,
    itemId: "l2",
  },
  {
    id: "n2",
    type: "recovery",
    title: "Item Recovered!",
    message: "Great news! Your golden bracelet has been reported found by a community member.",
    time: "1 hour ago",
    isRead: false,
    itemId: "l5",
  },
  {
    id: "n3",
    type: "alert",
    title: "Emergency Alert",
    message: "Multiple passport-related items reported lost at IGI Airport today. If you lost yours, report immediately.",
    time: "3 hours ago",
    isRead: true,
  },
  {
    id: "n4",
    type: "update",
    title: "Your Report Updated",
    message: "Your lost backpack report has been viewed 47 times and shared by 12 community members.",
    time: "Yesterday",
    isRead: true,
    itemId: "l1",
  },
  {
    id: "n5",
    type: "match",
    title: "New Match Alert",
    message: "A found wallet matching your description was submitted near City Mall. Check now.",
    time: "Yesterday",
    isRead: true,
    itemId: "l3",
  },
  {
    id: "n6",
    type: "update",
    title: "Community Update",
    message: "3 items in your area were successfully recovered this week thanks to MilGaya community.",
    time: "2 days ago",
    isRead: true,
  },
];

export const RECOVERY_STORIES: RecoveryStory[] = [
  {
    id: "s1",
    title: "Found My Lost Laptop After 3 Days!",
    description: "Lost my work laptop at the railway station. Thanks to MilGaya, a shop owner had kept it safe and we connected within hours. Incredible community!",
    helperName: "Rajesh Gupta",
    ownerName: "Ananya M.",
    date: "Jan 14, 2024",
    category: "Electronics",
    likes: 234,
  },
  {
    id: "s2",
    title: "Recovered Grandmother's Jewellery",
    description: "The gold chain had been with my family for 3 generations. I thought it was gone forever. MilGaya community members spread the word and a kind stranger found it at the park.",
    helperName: "Meena Aunty",
    ownerName: "Preethi K.",
    date: "Jan 10, 2024",
    category: "Jewellery",
    likes: 567,
  },
  {
    id: "s3",
    title: "Passport Back in Time for Flight!",
    description: "Lost my passport 12 hours before my international flight. Someone on MilGaya had already found it and was at the airport. Made my flight with 30 minutes to spare!",
    helperName: "Airport Volunteer",
    ownerName: "Vikram S.",
    date: "Jan 8, 2024",
    category: "Documents",
    likes: 891,
  },
];

export const TOP_HELPERS: TopHelper[] = [
  {
    id: "h1",
    name: "Rajesh Gupta",
    recoveries: 48,
    badge: "Gold Helper",
    rating: 4.9,
    location: "Koramangala",
  },
  {
    id: "h2",
    name: "Meena Sharma",
    recoveries: 35,
    badge: "Silver Helper",
    rating: 4.8,
    location: "Indiranagar",
  },
  {
    id: "h3",
    name: "Ali Hassan",
    recoveries: 29,
    badge: "Silver Helper",
    rating: 4.7,
    location: "Whitefield",
  },
  {
    id: "h4",
    name: "Sunita Rao",
    recoveries: 21,
    badge: "Bronze Helper",
    rating: 4.6,
    location: "HSR Layout",
  },
];

export const PARTNERS: Partner[] = [
  {
    id: "p1",
    name: "MG Road General Store",
    type: "shop",
    address: "42, MG Road, Near Metro Gate 2",
    distance: "0.3 km",
    rating: 4.8,
    totalItems: 23,
    isVerified: true,
    openNow: true,
    phone: "+91 98765 43210",
  },
  {
    id: "p2",
    name: "Delhi Public School",
    type: "school",
    address: "15, Indiranagar 5th Cross",
    distance: "1.2 km",
    rating: 4.9,
    totalItems: 67,
    isVerified: true,
    openNow: false,
    phone: "+91 80 2345 6789",
  },
  {
    id: "p3",
    name: "Cubbon Park Police Post",
    type: "police",
    address: "Cubbon Park, Kasturba Road",
    distance: "0.8 km",
    rating: 4.5,
    totalItems: 112,
    isVerified: true,
    openNow: true,
    phone: "100",
  },
  {
    id: "p4",
    name: "HP Petrol Pump",
    type: "petrol",
    address: "Residency Road Junction",
    distance: "0.5 km",
    rating: 4.3,
    totalItems: 8,
    isVerified: true,
    openNow: true,
    phone: "+91 98765 11122",
  },
  {
    id: "p5",
    name: "Manipal Hospital",
    type: "hospital",
    address: "98, HAL Airport Road",
    distance: "3.1 km",
    rating: 4.7,
    totalItems: 31,
    isVerified: true,
    openNow: true,
    phone: "+91 80 2502 4444",
  },
];

export const MAP_MARKERS: MapMarker[] = [
  { id: "l1", type: "lost", title: "Black Backpack", lat: 12.9716, lng: 77.5946, category: "Bags" },
  { id: "l2", type: "lost", title: "iPhone 15 Pro", lat: 12.935, lng: 77.6244, category: "Electronics" },
  { id: "l3", type: "lost", title: "Brown Wallet", lat: 12.9698, lng: 77.6101, category: "Wallet" },
  { id: "f1", type: "found", title: "Samsung Galaxy", lat: 12.979, lng: 77.5916, category: "Electronics" },
  { id: "f2", type: "found", title: "Blue Backpack", lat: 12.9784, lng: 77.6408, category: "Bags" },
  { id: "f3", type: "found", title: "Car Keys", lat: 12.934, lng: 77.6101, category: "Keys" },
];

export const FEED_POSTS: FeedPost[] = [
  {
    id: "fp1",
    type: "story",
    authorName: "Rajesh Gupta",
    authorSubtitle: "Gold Helper · 48 Recoveries",
    timeAgo: "2 hours ago",
    category: "Electronics",
    title: "Found My Lost Laptop After 3 Days!",
    body: "Lost my work laptop at the railway station and thought it was gone forever. Thanks to MilGaya, a shop owner had kept it safe and we connected within hours. The community spread my post and within 3 hours I had a match. Incredible community spirit!",
    location: "Bangalore City Railway Station",
    likes: 234,
    comments: 47,
    isVerified: true,
  },
  {
    id: "fp2",
    type: "lost",
    authorName: "Priya Sharma",
    authorSubtitle: "Koramangala, Bangalore",
    timeAgo: "4 hours ago",
    category: "Electronics",
    title: "Urgent: iPhone 15 Pro Lost at Metro Station",
    body: "Lost my iPhone 15 Pro with a blue cover case at Koramangala Metro Station. The screen has a small crack at the corner. It has important work data and photos. Please help if you've seen it. Happy to offer a reward.",
    location: "Koramangala Metro Station",
    likes: 89,
    comments: 23,
    reward: "₹5,000",
    isUrgent: true,
  },
  {
    id: "fp3",
    type: "found",
    authorName: "Amit Verma",
    authorSubtitle: "Verified Community Helper",
    timeAgo: "6 hours ago",
    category: "Electronics",
    title: "Found: Samsung Galaxy Phone Near Cubbon Park",
    body: "Found a Samsung Galaxy phone with a yellow silicone case near the East Gate of Cubbon Park. The phone is locked. I've handed it over to the Cubbon Park Police Station for safekeeping. If this is yours, please reach out with proof of ownership.",
    location: "Cubbon Park Police Station",
    likes: 156,
    comments: 31,
    isVerified: true,
  },
  {
    id: "fp4",
    type: "story",
    authorName: "Preethi K.",
    authorSubtitle: "Lalbagh, Bangalore",
    timeAgo: "1 day ago",
    category: "Jewellery",
    title: "Recovered My Grandmother's Gold Bracelet!",
    body: "My grandmother's 22-carat gold bracelet with traditional design and tiny bell charms slipped off at Lalbagh Botanical Garden. It has been in our family for 3 generations — I was devastated. A kind MilGaya member spotted my post and recognized the description. We met at the park gate and she returned it. I cried.",
    location: "Lalbagh Botanical Garden",
    likes: 567,
    comments: 89,
    isVerified: true,
  },
  {
    id: "fp5",
    type: "alert",
    authorName: "MilGaya Safety Team",
    authorSubtitle: "Official · Community Alert",
    timeAgo: "5 hours ago",
    category: "Documents",
    title: "Multiple Passports Lost at IGI Airport Today",
    body: "We've received 3 separate reports of passport loss at Indira Gandhi International Airport Terminal 2. If you've lost yours or found one, please report immediately. Airport Lost & Found is at Gate 4, Arrivals. Time is critical for travel documents.",
    location: "IGI Airport Terminal 2",
    likes: 312,
    comments: 67,
    isUrgent: true,
    isVerified: true,
  },
  {
    id: "fp6",
    type: "lost",
    authorName: "Arjun Singh",
    authorSubtitle: "City Mall, Bangalore",
    timeAgo: "1 day ago",
    category: "Wallet",
    title: "Lost: Brown Leather Wallet at City Mall Food Court",
    body: "Slim brown leather wallet with monogram 'AS' — lost at City Mall Food Court around 6:45 PM. Contains Aadhaar card, driving license, and some cash. The wallet itself isn't worth much but those documents are a pain to replace. Please help!",
    location: "City Mall Food Court",
    likes: 43,
    comments: 12,
  },
  {
    id: "fp7",
    type: "found",
    authorName: "Kavitha R.",
    authorSubtitle: "Indiranagar, Bangalore",
    timeAgo: "2 days ago",
    category: "Bags",
    title: "Found: Blue Denim Backpack at Indiranagar Bus Stop",
    body: "Found a blue denim backpack near Bus Stop 54 in Indiranagar this morning at 7:45 AM. The bag contains books and a water bottle. No wallet or electronics. I've kept it safe at the keeper's shop near the bus stop. Please come and collect if it's yours.",
    location: "Indiranagar Bus Stop 54",
    likes: 78,
    comments: 15,
    isVerified: true,
  },
  {
    id: "fp8",
    type: "story",
    authorName: "Vikram S.",
    authorSubtitle: "IGI Airport, Delhi",
    timeAgo: "3 days ago",
    category: "Documents",
    title: "Passport Back in Time for My International Flight!",
    body: "Lost my passport 12 hours before my international flight. I was in a complete panic — visa, tickets, everything was sorted but no passport. Posted on MilGaya and within 2 hours someone had already found it. They were also at the airport! Made my flight with 30 minutes to spare. This app literally changed my life.",
    location: "Indira Gandhi Airport",
    likes: 891,
    comments: 143,
    isVerified: true,
  },
  {
    id: "fp9",
    type: "lost",
    authorName: "Neha Patel",
    authorSubtitle: "Brigade Road, Bangalore",
    timeAgo: "3 days ago",
    category: "Keys",
    title: "Lost Honda Activa Keys on Brigade Road",
    body: "Lost my Honda Activa key with a blue key ring and a small Ganesha charm near Brigade Road Junction around 11 AM. The key ring also has my house keys. Without these I'm stranded — my spare is at my parents' place in another city. Please help!",
    location: "Brigade Road Junction",
    likes: 29,
    comments: 8,
    reward: "₹500",
  },
  {
    id: "fp10",
    type: "found",
    authorName: "Security Guard",
    authorSubtitle: "Forum Mall, Bangalore",
    timeAgo: "4 days ago",
    category: "Keys",
    title: "Toyota Car Keys Found at Forum Mall Parking",
    body: "Toyota car keys with a black key fob and a small keychain found in Forum Mall Parking Level B2 around 1:20 PM. Handed over to the Forum Mall Security Office. Owner can collect by showing car registration papers as proof.",
    location: "Forum Mall Security Office",
    likes: 52,
    comments: 9,
    isVerified: true,
  },
];
