const colors = {
  light: {
    text: "#1A1D2E",
    tint: "#5B67FF",
    background: "#F5F6FA",
    foreground: "#1A1D2E",
    card: "#FFFFFF",
    cardForeground: "#1A1D2E",
    primary: "#5B67FF",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF0FF",
    secondaryForeground: "#5B67FF",
    muted: "#F0F2F8",
    mutedForeground: "#8A90A2",
    accent: "#00BFA5",
    accentForeground: "#FFFFFF",
    destructive: "#FF4757",
    destructiveForeground: "#FFFFFF",
    border: "#E8EAF2",
    input: "#F0F2F8",
    warning: "#FFA502",
    warningForeground: "#FFFFFF",
    success: "#2ED573",
    successForeground: "#FFFFFF",
    tabBar: "#FFFFFF",
    headerBg: "#FFFFFF",
    overlayBg: "rgba(26,29,46,0.5)",
    gradientPrimary: ["#5B67FF", "#8B94FF"] as const,
    gradientAccent: ["#00BFA5", "#00E5C6"] as const,
    gradientDestructive: ["#FF4757", "#FF7F8A"] as const,
  },
  dark: {
    text: "#F0F2FA",
    tint: "#7B86FF",
    background: "#0E0F1A",
    foreground: "#F0F2FA",
    card: "#181A2E",
    cardForeground: "#F0F2FA",
    primary: "#7B86FF",
    primaryForeground: "#0E0F1A",
    secondary: "#1A1D35",
    secondaryForeground: "#7B86FF",
    muted: "#1A1D35",
    mutedForeground: "#5D637A",
    accent: "#00C4AA",
    accentForeground: "#0E0F1A",
    destructive: "#FF6B78",
    destructiveForeground: "#0E0F1A",
    border: "#252842",
    input: "#252842",
    warning: "#FFB830",
    warningForeground: "#0E0F1A",
    success: "#3DDB89",
    successForeground: "#0E0F1A",
    tabBar: "#181A2E",
    headerBg: "#181A2E",
    overlayBg: "rgba(0,0,0,0.72)",
    gradientPrimary: ["#7B86FF", "#A0A8FF"] as const,
    gradientAccent: ["#00C4AA", "#1AEAD0"] as const,
    gradientDestructive: ["#FF6B78", "#FFA0A9"] as const,
  },
  radius: 14,
};

export default colors;
